root: true
targets:
    'easy_install':
        shell: |
            export PATH=/usr/local/bin/python:$PATH
            easy_install .

    'deploy pypitest':
        shell: |
            export PATH=/usr/local/bin/python:$PATH
            python setup.py sdist upload -r pypitest

    'deploy pypi':
        shell: |
            export PATH=/usr/local/bin/python:$PATH
            python setup.py sdist upload -r pypi
